#INI_SETTINGS
JSON_FILENAME = 'config.json'
SERVER = 'MSSQLSERVER'

#QUOTE_WRAPS
DQUOTES = 'dQuotes'
SQUOTES = 'sQuotes'
CBRACKETS = 'cBrackets'
SBRACKETS ='sBrackets'
XML = 'XML'
PARAENTHESES ='parentheses'

#DATE_FORMAT
DT_FMT = '%Y-%m-%d %H:%M:%S'

# SQL_STATEMENT_TYPES
DQL = 'DQL'
DML = 'DML'
DDL = 'DDL'

#REGEX_OPTIONS
REGEX_REPLACE = 'REGEX_REPLACE'
REGEX_RETURN = 'REGEX_RETURN'

#COMMON_REGEX_PATTERNS
REGEX_FILE_PATH = '.*\\\\'
REGEX_FILE_EXT = r'[^\.]\w*$'

#REDDIT_TYPES
REDDIT_TYPES = {
'REDDIT_COMMENT':'t1_',
'REDDIT_ACCOUNT':'t2_',
'REDDIT_LINK':'t3_',
'REDDIT_MESSAGE':'t4_',
'REDDIT_SUBREDDIT':'t5_',
'REDDIT_AWARD':'t6_'
}

REDDIT_COMMENT = 't1_'
REDDIT_ACCOUNT = 't2_'
REDDIT_LINK = 't3_'
REDDIT_MESSAGE = 't4_'
REDDIT_SUBREDDIT = 't5_'
REDDIT_AWARD = 't6_'

#VALUE_RETURN_OPTIONS
FOR_BOOL = 0
FOR_VAL = 1

#ARRAY_RETURN_OPTIONS
FIRST_ITEM = 0
SECOND_ITEM = 1